function generateSentence() {
    const nouns = [
      document.getElementById("noun1").value,
      document.getElementById("noun2").value,
      document.getElementById("noun3").value,
      document.getElementById("noun4").value,
      document.getElementById("noun5").value,
    ];
  
    const adjectives = [
      "red",
      "blue",
      "green",
      "happy",
      "sad",
      "angry",
      "silly",
      "serious",
      "playful",
      "curious",
      "hot",
      "annoyed",
      "strong",
      "comprehensive",
      "private",
      "giant",
      "smelly",
      "special",
      "tightfisted",
      "greasy",
      "barbarous",
      "cautious",
      "faded", 
      "lazy", 
      "humdrum",
      "impressive",
      "healthy",
      "roomy",
      "wet",
      "grateful",
      "fair",
      "absent",
      "extra-small",
      "zealous",
      "average",
      "hanging",
      "kindhearted",
      "drunk", 
      "equable", 
      "spotted", 
      "ludicrous", 
      "long",
      "questionable", 
      "ambiguous",
      "psychological",
      "opposite",
      "quiet",
      "educational",
      "empty",
      "damaged",
      "simple",
      "assorted"
    ];
  
    const verbs = [
      "ran",
      "jumped",
      "ate",
      "slept",
      "cooked",
      "laughed",
      "cried",
      "danced",
      "sang",
      "talked",
      "listened",
      "cater",
      "spin",
      "favour",
      "weaken",
      "attain",
      "beat",
      "admire",
      "behave",
      "impress",
      "consider",
      "lend",
      "justify",
      "commence",
      "stand",
      "solve",
      "pray",
      "fancy",
      "approve",
      "see",
      "throw",
      "favour",
      "exclude",
      "allow",
      "replace",
      "suspend",
      "present",
      "worry",
      "swear",
      "train",
      "expect",
      "reflect",
      "exhaust",
      "swallow",
      "suffer",
      "strike",
      "suit",
      "enquire",
      "tear",
      "hire",
      "proceed"
    ];
  
    const randomNoun1 = nouns[Math.floor(Math.random() * nouns.length)];
    const randomAdjective1 = adjectives[Math.floor(Math.random() * adjectives.length)];
    const randomVerb1 = verbs[Math.floor(Math.random() * verbs.length)];
    const randomNoun2 = nouns[Math.floor(Math.random() * nouns.length)];
    const randomAdjective2 = adjectives[Math.floor(Math.random() * adjectives.length)];
    const randomVerb2 = verbs[Math.floor(Math.random() * verbs.length)];

    const sentence = `The ${randomAdjective1} ${randomNoun1} ${randomVerb1} and ${randomAdjective2} ${randomNoun2} ${randomVerb2}.`;
  
    document.getElementById("sentence").textContent = sentence;
  }
  